config/routes.rb
Fis::Application.routes.draw do
  resources :absences

  resources :char_refs

  resources :load_assign_in_others

  resources :publications_and_researches

  resources :professional_memberships

  resources :non_teaching_experiences

  resources :teaching_experiences

  resources :civil_service_and_govt_exams

  resources :educational_attainments

  resources :children

  resources :faculties

  resources :versions

  get "website/index"

  controller :website do
    get 'howto' => :howto
  end
  

  root :to => 'website#index', :as => 'website'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/absence.rb
class Absence < ActiveRecord::Base
  belongs_to :faculty
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/char_ref.rb
class CharRef < ActiveRecord::Base
  belongs_to :faculty
end

app/models/child.rb
class Child < ActiveRecord::Base
  belongs_to :faculty
end

app/models/educational_attainment.rb
class EducationalAttainment < ActiveRecord::Base
  belongs_to :faculty



end

app/models/faculty.rb
class Faculty < ActiveRecord::Base
	has_paper_trail :only => [:academic_rank,  :faculty_status, :faculty_status2, :pagibig, :tbi, :department]

	has_many :children, :dependent => :destroy

	validates :last_name, :first_name, :presence => true

	accepts_nested_attributes_for :children, :reject_if => :all_blank, :allow_destroy => true

	def fullname
		"#{self.last_name}, #{self.first_name}"
	end
end

app/models/load_assign_in_other.rb
class LoadAssignInOther < ActiveRecord::Base
  belongs_to :faculty
end

app/models/non_teaching_experience.rb
class NonTeachingExperience < ActiveRecord::Base
  belongs_to :faculty
end

app/models/professional_membership.rb
class ProfessionalMembership < ActiveRecord::Base
  belongs_to :faculty
end

app/models/teaching_experience.rb
class TeachingExperience < ActiveRecord::Base
  belongs_to :faculty
end

app/controllers/absences_controller.rb
class AbsencesController < InheritedResources::Base
end

app/controllers/char_refs_controller.rb
class CharRefsController < InheritedResources::Base
end

app/controllers/children_controller.rb
class ChildrenController < InheritedResources::Base
end

app/controllers/educational_attainments_controller.rb
class EducationalAttainmentsController < InheritedResources::Base
end

app/controllers/faculties_controller.rb
class FacultiesController < InheritedResources::Base

	
end

app/controllers/versions_controller.rb
class VersionsController < InheritedResources::Base
end

app/controllers/website_controller.rb
class WebsiteController < ApplicationController
  def index
    @faculties = Faculty.take(15)
    @versions = PaperTrail::Version.all
  end

  def howto
  end
  
end

app/helpers/absences_helper.rb
module AbsencesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper


	
end

app/helpers/char_refs_helper.rb
module CharRefsHelper
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/helpers/educational_attainments_helper.rb
module EducationalAttainmentsHelper
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/views/educational_attainments/_form.html.erb
<%= form_for(@educational_attainment) do |f| %>
  <% if @educational_attainment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@educational_attainment.errors.count, "error") %> prohibited this educational_attainment from being saved:</h2>

      <ul>
      <% @educational_attainment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :faculty_id %><br>
    <%= f.text_field :faculty_id %>
  </div>
  <div class="field">
    <%= f.label :school_name_elemetary %><br>
    <%= f.text_field :school_name_elemetary %>
  </div>
  <div class="field">
    <%= f.label :school_location_elementary %><br>
    <%= f.text_field :school_location_elementary %>
  </div>
  <div class="field">
    <%= f.label :school_yearfrom_elementary %><br>
    <%= f.datetime_select :school_yearfrom_elementary %>
  </div>
  <div class="field">
    <%= f.label :school_yearto_elementary %><br>
    <%= f.datetime_select :school_yearto_elementary %>
  </div>
  <div class="field">
    <%= f.label :school_degrees_elementary %><br>
    <%= f.text_field :school_degrees_elementary %>
  </div>
  <div class="field">
    <%= f.label :school_honors_elementary %><br>
    <%= f.text_field :school_honors_elementary %>
  </div>
  <div class="field">
    <%= f.label :school_name_intermediate %><br>
    <%= f.text_field :school_name_intermediate %>
  </div>
  <div class="field">
    <%= f.label :school_location_intermediate %><br>
    <%= f.text_field :school_location_intermediate %>
  </div>
  <div class="field">
    <%= f.label :school_yearfrom_intermediate %><br>
    <%= f.datetime_select :school_yearfrom_intermediate %>
  </div>
  <div class="field">
    <%= f.label :school_yearto_intermediate %><br>
    <%= f.datetime_select :school_yearto_intermediate %>
  </div>
  <div class="field">
    <%= f.label :school_degrees_intermediate %><br>
    <%= f.text_field :school_degrees_intermediate %>
  </div>
  <div class="field">
    <%= f.label :school_honors_intermediate %><br>
    <%= f.text_field :school_honors_intermediate %>
  </div>
  <div class="field">
    <%= f.label :school_name_secondary %><br>
    <%= f.text_field :school_name_secondary %>
  </div>
  <div class="field">
    <%= f.label :school_location_secondary %><br>
    <%= f.text_field :school_location_secondary %>
  </div>
  <div class="field">
    <%= f.label :school_yearfrom_secondary %><br>
    <%= f.datetime_select :school_yearfrom_secondary %>
  </div>
  <div class="field">
    <%= f.label :school_yearto_secondary %><br>
    <%= f.datetime_select :school_yearto_secondary %>
  </div>
  <div class="field">
    <%= f.label :school_degrees_secondary %><br>
    <%= f.text_field :school_degrees_secondary %>
  </div>
  <div class="field">
    <%= f.label :school_honors_secondary %><br>
    <%= f.text_field :school_honors_secondary %>
  </div>
  <div class="field">
    <%= f.label :school_name_collegiate %><br>
    <%= f.text_field :school_name_collegiate %>
  </div>
  <div class="field">
    <%= f.label :school_location_collegiate %><br>
    <%= f.text_field :school_location_collegiate %>
  </div>
  <div class="field">
    <%= f.label :school_yearfrom_collegiate %><br>
    <%= f.datetime_select :school_yearfrom_collegiate %>
  </div>
  <div class="field">
    <%= f.label :school_yearto_collegiate %><br>
    <%= f.datetime_select :school_yearto_collegiate %>
  </div>
  <div class="field">
    <%= f.label :school_degrees_collegiate %><br>
    <%= f.text_field :school_degrees_collegiate %>
  </div>
  <div class="field">
    <%= f.label :school_honors_collegiate %><br>
    <%= f.text_field :school_honors_collegiate %>
  </div>
  <div class="field">
    <%= f.label :school_name_graduate %><br>
    <%= f.text_field :school_name_graduate %>
  </div>
  <div class="field">
    <%= f.label :school_location_graduate %><br>
    <%= f.text_field :school_location_graduate %>
  </div>
  <div class="field">
    <%= f.label :school_yearfrom_graduate %><br>
    <%= f.datetime_select :school_yearfrom_graduate %>
  </div>
  <div class="field">
    <%= f.label :school_yearto_graduate %><br>
    <%= f.datetime_select :school_yearto_graduate %>
  </div>
  <div class="field">
    <%= f.label :school_degrees_graduate %><br>
    <%= f.text_field :school_degrees_graduate %>
  </div>
  <div class="field">
    <%= f.label :school_honors_graduate %><br>
    <%= f.text_field :school_honors_graduate %>
  </div>
  <div class="field">
    <%= f.label :school_name_doctoral %><br>
    <%= f.text_field :school_name_doctoral %>
  </div>
  <div class="field">
    <%= f.label :school_location_doctoral %><br>
    <%= f.text_field :school_location_doctoral %>
  </div>
  <div class="field">
    <%= f.label :school_yearfrom_doctoral %><br>
    <%= f.datetime_select :school_yearfrom_doctoral %>
  </div>
  <div class="field">
    <%= f.label :school_yearto_doctoral %><br>
    <%= f.datetime_select :school_yearto_doctoral %>
  </div>
  <div class="field">
    <%= f.label :school_degrees_doctoral %><br>
    <%= f.text_field :school_degrees_doctoral %>
  </div>
  <div class="field">
    <%= f.label :school_honors_doctoral %><br>
    <%= f.text_field :school_honors_doctoral %>
  </div>
  <div class="field">
    <%= f.label :college_major %><br>
    <%= f.text_field :college_major %>
  </div>
  <div class="field">
    <%= f.label :college_minor %><br>
    <%= f.text_field :college_minor %>
  </div>
  <div class="field">
    <%= f.label :special_studies %><br>
    <%= f.text_field :special_studies %>
  </div>
  <div class="field">
    <%= f.label :present_studies %><br>
    <%= f.text_field :present_studies %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/educational_attainments/edit.html.erb
<h1>Editing educational_attainment</h1>

<%= render 'form' %>

<%= link_to 'Show', @educational_attainment %> |
<%= link_to 'Back', educational_attainments_path %>

app/views/educational_attainments/index.html.erb
<h1>Listing educational_attainments</h1>

<table>
  <thead>
    <tr>
      <th>Faculty</th>
      <th>School name elemetary</th>
      <th>School location elementary</th>
      <th>School yearfrom elementary</th>
      <th>School yearto elementary</th>
      <th>School degrees elementary</th>
      <th>School honors elementary</th>
      <th>School name intermediate</th>
      <th>School location intermediate</th>
      <th>School yearfrom intermediate</th>
      <th>School yearto intermediate</th>
      <th>School degrees intermediate</th>
      <th>School honors intermediate</th>
      <th>School name secondary</th>
      <th>School location secondary</th>
      <th>School yearfrom secondary</th>
      <th>School yearto secondary</th>
      <th>School degrees secondary</th>
      <th>School honors secondary</th>
      <th>School name collegiate</th>
      <th>School location collegiate</th>
      <th>School yearfrom collegiate</th>
      <th>School yearto collegiate</th>
      <th>School degrees collegiate</th>
      <th>School honors collegiate</th>
      <th>School name graduate</th>
      <th>School location graduate</th>
      <th>School yearfrom graduate</th>
      <th>School yearto graduate</th>
      <th>School degrees graduate</th>
      <th>School honors graduate</th>
      <th>School name doctoral</th>
      <th>School location doctoral</th>
      <th>School yearfrom doctoral</th>
      <th>School yearto doctoral</th>
      <th>School degrees doctoral</th>
      <th>School honors doctoral</th>
      <th>College major</th>
      <th>College minor</th>
      <th>Special studies</th>
      <th>Present studies</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @educational_attainments.each do |educational_attainment| %>
      <tr>
        <td><%= educational_attainment.faculty %></td>
        <td><%= educational_attainment.school_name_elemetary %></td>
        <td><%= educational_attainment.school_location_elementary %></td>
        <td><%= educational_attainment.school_yearfrom_elementary %></td>
        <td><%= educational_attainment.school_yearto_elementary %></td>
        <td><%= educational_attainment.school_degrees_elementary %></td>
        <td><%= educational_attainment.school_honors_elementary %></td>
        <td><%= educational_attainment.school_name_intermediate %></td>
        <td><%= educational_attainment.school_location_intermediate %></td>
        <td><%= educational_attainment.school_yearfrom_intermediate %></td>
        <td><%= educational_attainment.school_yearto_intermediate %></td>
        <td><%= educational_attainment.school_degrees_intermediate %></td>
        <td><%= educational_attainment.school_honors_intermediate %></td>
        <td><%= educational_attainment.school_name_secondary %></td>
        <td><%= educational_attainment.school_location_secondary %></td>
        <td><%= educational_attainment.school_yearfrom_secondary %></td>
        <td><%= educational_attainment.school_yearto_secondary %></td>
        <td><%= educational_attainment.school_degrees_secondary %></td>
        <td><%= educational_attainment.school_honors_secondary %></td>
        <td><%= educational_attainment.school_name_collegiate %></td>
        <td><%= educational_attainment.school_location_collegiate %></td>
        <td><%= educational_attainment.school_yearfrom_collegiate %></td>
        <td><%= educational_attainment.school_yearto_collegiate %></td>
        <td><%= educational_attainment.school_degrees_collegiate %></td>
        <td><%= educational_attainment.school_honors_collegiate %></td>
        <td><%= educational_attainment.school_name_graduate %></td>
        <td><%= educational_attainment.school_location_graduate %></td>
        <td><%= educational_attainment.school_yearfrom_graduate %></td>
        <td><%= educational_attainment.school_yearto_graduate %></td>
        <td><%= educational_attainment.school_degrees_graduate %></td>
        <td><%= educational_attainment.school_honors_graduate %></td>
        <td><%= educational_attainment.school_name_doctoral %></td>
        <td><%= educational_attainment.school_location_doctoral %></td>
        <td><%= educational_attainment.school_yearfrom_doctoral %></td>
        <td><%= educational_attainment.school_yearto_doctoral %></td>
        <td><%= educational_attainment.school_degrees_doctoral %></td>
        <td><%= educational_attainment.school_honors_doctoral %></td>
        <td><%= educational_attainment.college_major %></td>
        <td><%= educational_attainment.college_minor %></td>
        <td><%= educational_attainment.special_studies %></td>
        <td><%= educational_attainment.present_studies %></td>
        <td><%= link_to 'Show', educational_attainment %></td>
        <td><%= link_to 'Edit', edit_educational_attainment_path(educational_attainment) %></td>
        <td><%= link_to 'Destroy', educational_attainment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Educational attainment', new_educational_attainment_path %>

app/views/educational_attainments/new.html.erb
<h1>New educational_attainment</h1>

<%= render 'form' %>

<%= link_to 'Back', educational_attainments_path %>

app/views/educational_attainments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Faculty:</strong>
  <%= @educational_attainment.faculty %>
</p>

<p>
  <strong>School name elemetary:</strong>
  <%= @educational_attainment.school_name_elemetary %>
</p>

<p>
  <strong>School location elementary:</strong>
  <%= @educational_attainment.school_location_elementary %>
</p>

<p>
  <strong>School yearfrom elementary:</strong>
  <%= @educational_attainment.school_yearfrom_elementary %>
</p>

<p>
  <strong>School yearto elementary:</strong>
  <%= @educational_attainment.school_yearto_elementary %>
</p>

<p>
  <strong>School degrees elementary:</strong>
  <%= @educational_attainment.school_degrees_elementary %>
</p>

<p>
  <strong>School honors elementary:</strong>
  <%= @educational_attainment.school_honors_elementary %>
</p>

<p>
  <strong>School name intermediate:</strong>
  <%= @educational_attainment.school_name_intermediate %>
</p>

<p>
  <strong>School location intermediate:</strong>
  <%= @educational_attainment.school_location_intermediate %>
</p>

<p>
  <strong>School yearfrom intermediate:</strong>
  <%= @educational_attainment.school_yearfrom_intermediate %>
</p>

<p>
  <strong>School yearto intermediate:</strong>
  <%= @educational_attainment.school_yearto_intermediate %>
</p>

<p>
  <strong>School degrees intermediate:</strong>
  <%= @educational_attainment.school_degrees_intermediate %>
</p>

<p>
  <strong>School honors intermediate:</strong>
  <%= @educational_attainment.school_honors_intermediate %>
</p>

<p>
  <strong>School name secondary:</strong>
  <%= @educational_attainment.school_name_secondary %>
</p>

<p>
  <strong>School location secondary:</strong>
  <%= @educational_attainment.school_location_secondary %>
</p>

<p>
  <strong>School yearfrom secondary:</strong>
  <%= @educational_attainment.school_yearfrom_secondary %>
</p>

<p>
  <strong>School yearto secondary:</strong>
  <%= @educational_attainment.school_yearto_secondary %>
</p>

<p>
  <strong>School degrees secondary:</strong>
  <%= @educational_attainment.school_degrees_secondary %>
</p>

<p>
  <strong>School honors secondary:</strong>
  <%= @educational_attainment.school_honors_secondary %>
</p>

<p>
  <strong>School name collegiate:</strong>
  <%= @educational_attainment.school_name_collegiate %>
</p>

<p>
  <strong>School location collegiate:</strong>
  <%= @educational_attainment.school_location_collegiate %>
</p>

<p>
  <strong>School yearfrom collegiate:</strong>
  <%= @educational_attainment.school_yearfrom_collegiate %>
</p>

<p>
  <strong>School yearto collegiate:</strong>
  <%= @educational_attainment.school_yearto_collegiate %>
</p>

<p>
  <strong>School degrees collegiate:</strong>
  <%= @educational_attainment.school_degrees_collegiate %>
</p>

<p>
  <strong>School honors collegiate:</strong>
  <%= @educational_attainment.school_honors_collegiate %>
</p>

<p>
  <strong>School name graduate:</strong>
  <%= @educational_attainment.school_name_graduate %>
</p>

<p>
  <strong>School location graduate:</strong>
  <%= @educational_attainment.school_location_graduate %>
</p>

<p>
  <strong>School yearfrom graduate:</strong>
  <%= @educational_attainment.school_yearfrom_graduate %>
</p>

<p>
  <strong>School yearto graduate:</strong>
  <%= @educational_attainment.school_yearto_graduate %>
</p>

<p>
  <strong>School degrees graduate:</strong>
  <%= @educational_attainment.school_degrees_graduate %>
</p>

<p>
  <strong>School honors graduate:</strong>
  <%= @educational_attainment.school_honors_graduate %>
</p>

<p>
  <strong>School name doctoral:</strong>
  <%= @educational_attainment.school_name_doctoral %>
</p>

<p>
  <strong>School location doctoral:</strong>
  <%= @educational_attainment.school_location_doctoral %>
</p>

<p>
  <strong>School yearfrom doctoral:</strong>
  <%= @educational_attainment.school_yearfrom_doctoral %>
</p>

<p>
  <strong>School yearto doctoral:</strong>
  <%= @educational_attainment.school_yearto_doctoral %>
</p>

<p>
  <strong>School degrees doctoral:</strong>
  <%= @educational_attainment.school_degrees_doctoral %>
</p>

<p>
  <strong>School honors doctoral:</strong>
  <%= @educational_attainment.school_honors_doctoral %>
</p>

<p>
  <strong>College major:</strong>
  <%= @educational_attainment.college_major %>
</p>

<p>
  <strong>College minor:</strong>
  <%= @educational_attainment.college_minor %>
</p>

<p>
  <strong>Special studies:</strong>
  <%= @educational_attainment.special_studies %>
</p>

<p>
  <strong>Present studies:</strong>
  <%= @educational_attainment.present_studies %>
</p>

<%= link_to 'Edit', edit_educational_attainment_path(@educational_attainment) %> |
<%= link_to 'Back', educational_attainments_path %>