config/routes.rb
Fis::Application.routes.draw do
  resources :absences

  resources :char_refs

  resources :load_assign_in_others

  resources :publications_and_researches

  resources :professional_memberships

  resources :non_teaching_experiences

  resources :teaching_experiences

  resources :civil_service_and_govt_exams

  resources :educational_attainments

  resources :children

  resources :faculties

  resources :versions

  get "website/index"

  controller :website do
    get 'howto' => :howto
  end
  

  root :to => 'website#index', :as => 'website'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/absence.rb
class Absence < ActiveRecord::Base
  belongs_to :faculty
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/char_ref.rb
class CharRef < ActiveRecord::Base
  belongs_to :faculty
end

app/models/child.rb
class Child < ActiveRecord::Base
  belongs_to :faculty
end

app/models/educational_attainment.rb
class EducationalAttainment < ActiveRecord::Base
  belongs_to :faculty



end

app/models/faculty.rb
class Faculty < ActiveRecord::Base
	has_paper_trail :only => [:academic_rank,  :faculty_status, :faculty_status2, :pagibig, :tbi, :department]

	has_many :children, :dependent => :destroy

	validates :last_name, :first_name, :presence => true

	accepts_nested_attributes_for :children, :reject_if => :all_blank, :allow_destroy => true

	def fullname
		"#{self.last_name}, #{self.first_name}"
	end
end

app/models/load_assign_in_other.rb
class LoadAssignInOther < ActiveRecord::Base
  belongs_to :faculty
end

app/models/non_teaching_experience.rb
class NonTeachingExperience < ActiveRecord::Base
  belongs_to :faculty
end

app/models/professional_membership.rb
class ProfessionalMembership < ActiveRecord::Base
  belongs_to :faculty
end

app/models/teaching_experience.rb
class TeachingExperience < ActiveRecord::Base
  belongs_to :faculty
end

app/controllers/absences_controller.rb
class AbsencesController < InheritedResources::Base
end

app/controllers/char_refs_controller.rb
class CharRefsController < InheritedResources::Base
end

app/controllers/children_controller.rb
class ChildrenController < InheritedResources::Base
end

app/controllers/faculties_controller.rb
class FacultiesController < InheritedResources::Base

	
end

app/controllers/professional_memberships_controller.rb
class ProfessionalMembershipsController < InheritedResources::Base
end

app/controllers/versions_controller.rb
class VersionsController < InheritedResources::Base
end

app/controllers/website_controller.rb
class WebsiteController < ApplicationController
  def index
    @faculties = Faculty.take(15)
    @versions = PaperTrail::Version.all
  end

  def howto
  end
  
end

app/helpers/absences_helper.rb
module AbsencesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper


	
end

app/helpers/char_refs_helper.rb
module CharRefsHelper
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/helpers/professional_memberships_helper.rb
module ProfessionalMembershipsHelper
end

app/views/professional_memberships/_form.html.erb
<%= form_for(@professional_membership) do |f| %>
  <% if @professional_membership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@professional_membership.errors.count, "error") %> prohibited this professional_membership from being saved:</h2>

      <ul>
      <% @professional_membership.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :faculty_id %><br>
    <%= f.text_field :faculty_id %>
  </div>
  <div class="field">
    <%= f.label :org_name %><br>
    <%= f.text_field :org_name %>
  </div>
  <div class="field">
    <%= f.label :membership_date %><br>
    <%= f.datetime_select :membership_date %>
  </div>
  <div class="field">
    <%= f.label :no_of_yrs %><br>
    <%= f.number_field :no_of_yrs %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.text_field :position %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/professional_memberships/edit.html.erb
<h1>Editing professional_membership</h1>

<%= render 'form' %>

<%= link_to 'Show', @professional_membership %> |
<%= link_to 'Back', professional_memberships_path %>

app/views/professional_memberships/index.html.erb
<h1>Listing professional_memberships</h1>

<table>
  <thead>
    <tr>
      <th>Faculty</th>
      <th>Org name</th>
      <th>Membership date</th>
      <th>No of yrs</th>
      <th>Position</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @professional_memberships.each do |professional_membership| %>
      <tr>
        <td><%= professional_membership.faculty %></td>
        <td><%= professional_membership.org_name %></td>
        <td><%= professional_membership.membership_date %></td>
        <td><%= professional_membership.no_of_yrs %></td>
        <td><%= professional_membership.position %></td>
        <td><%= link_to 'Show', professional_membership %></td>
        <td><%= link_to 'Edit', edit_professional_membership_path(professional_membership) %></td>
        <td><%= link_to 'Destroy', professional_membership, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Professional membership', new_professional_membership_path %>

app/views/professional_memberships/new.html.erb
<h1>New professional_membership</h1>

<%= render 'form' %>

<%= link_to 'Back', professional_memberships_path %>

app/views/professional_memberships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Faculty:</strong>
  <%= @professional_membership.faculty %>
</p>

<p>
  <strong>Org name:</strong>
  <%= @professional_membership.org_name %>
</p>

<p>
  <strong>Membership date:</strong>
  <%= @professional_membership.membership_date %>
</p>

<p>
  <strong>No of yrs:</strong>
  <%= @professional_membership.no_of_yrs %>
</p>

<p>
  <strong>Position:</strong>
  <%= @professional_membership.position %>
</p>

<%= link_to 'Edit', edit_professional_membership_path(@professional_membership) %> |
<%= link_to 'Back', professional_memberships_path %>