config/routes.rb
Fis::Application.routes.draw do
  resources :absences

  resources :char_refs

  resources :load_assign_in_others

  resources :publications_and_researches

  resources :professional_memberships

  resources :non_teaching_experiences

  resources :teaching_experiences

  resources :civil_service_and_govt_exams

  resources :educational_attainments

  resources :children

  resources :faculties

  resources :versions

  get "website/index"

  controller :website do
    get 'howto' => :howto
  end
  

  root :to => 'website#index', :as => 'website'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/absence.rb
class Absence < ActiveRecord::Base
  belongs_to :faculty
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/char_ref.rb
class CharRef < ActiveRecord::Base
  belongs_to :faculty
end

app/models/child.rb
class Child < ActiveRecord::Base
  belongs_to :faculty
end

app/models/educational_attainment.rb
class EducationalAttainment < ActiveRecord::Base
  belongs_to :faculty



end

app/models/faculty.rb
class Faculty < ActiveRecord::Base
	has_paper_trail :only => [:academic_rank,  :faculty_status, :faculty_status2, :pagibig, :tbi, :department]

	has_many :children, :dependent => :destroy

	validates :last_name, :first_name, :presence => true

	accepts_nested_attributes_for :children, :reject_if => :all_blank, :allow_destroy => true

	def fullname
		"#{self.last_name}, #{self.first_name}"
	end
end

app/models/load_assign_in_other.rb
class LoadAssignInOther < ActiveRecord::Base
  belongs_to :faculty
end

app/models/non_teaching_experience.rb
class NonTeachingExperience < ActiveRecord::Base
  belongs_to :faculty
end

app/models/professional_membership.rb
class ProfessionalMembership < ActiveRecord::Base
  belongs_to :faculty
end

app/models/publications_and_research.rb
class PublicationsAndResearch < ActiveRecord::Base
  belongs_to :faculty




end

app/models/teaching_experience.rb
class TeachingExperience < ActiveRecord::Base
  belongs_to :faculty
end

app/controllers/absences_controller.rb
class AbsencesController < InheritedResources::Base
end

app/controllers/char_refs_controller.rb
class CharRefsController < InheritedResources::Base
end

app/controllers/children_controller.rb
class ChildrenController < InheritedResources::Base
end

app/controllers/publications_and_researches_controller.rb
class PublicationsAndResearchesController < InheritedResources::Base
end

app/controllers/versions_controller.rb
class VersionsController < InheritedResources::Base
end

app/controllers/website_controller.rb
class WebsiteController < ApplicationController
  def index
    @faculties = Faculty.take(15)
    @versions = PaperTrail::Version.all
  end

  def howto
  end
  
end

app/helpers/absences_helper.rb
module AbsencesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper


	
end

app/helpers/char_refs_helper.rb
module CharRefsHelper
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/helpers/publications_and_researches_helper.rb
module PublicationsAndResearchesHelper
end

app/views/publications_and_researches/_form.html.erb
<%= form_for(@publications_and_research) do |f| %>
  <% if @publications_and_research.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@publications_and_research.errors.count, "error") %> prohibited this publications_and_research from being saved:</h2>

      <ul>
      <% @publications_and_research.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :faculty_id %><br>
    <%= f.text_field :faculty_id %>
  </div>
  <div class="field">
    <%= f.label :organ_name %><br>
    <%= f.text_field :organ_name %>
  </div>
  <div class="field">
    <%= f.label :material_type %><br>
    <%= f.text_field :material_type %>
  </div>
  <div class="field">
    <%= f.label :publication_date %><br>
    <%= f.datetime_select :publication_date %>
  </div>
  <div class="field">
    <%= f.label :authorship_type %><br>
    <%= f.text_field :authorship_type %>
  </div>
  <div class="field">
    <%= f.label :co_author %><br>
    <%= f.text_field :co_author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/publications_and_researches/edit.html.erb
<h1>Editing publications_and_research</h1>

<%= render 'form' %>

<%= link_to 'Show', @publications_and_research %> |
<%= link_to 'Back', publications_and_researches_path %>

app/views/publications_and_researches/index.html.erb
<h1>Listing publications_and_researches</h1>

<table>
  <thead>
    <tr>
      <th>Faculty</th>
      <th>Organ name</th>
      <th>Material type</th>
      <th>Publication date</th>
      <th>Authorship type</th>
      <th>Co author</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @publications_and_researches.each do |publications_and_research| %>
      <tr>
        <td><%= publications_and_research.faculty %></td>
        <td><%= publications_and_research.organ_name %></td>
        <td><%= publications_and_research.material_type %></td>
        <td><%= publications_and_research.publication_date %></td>
        <td><%= publications_and_research.authorship_type %></td>
        <td><%= publications_and_research.co_author %></td>
        <td><%= link_to 'Show', publications_and_research %></td>
        <td><%= link_to 'Edit', edit_publications_and_research_path(publications_and_research) %></td>
        <td><%= link_to 'Destroy', publications_and_research, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Publications and research', new_publications_and_research_path %>

app/views/publications_and_researches/new.html.erb
<h1>New publications_and_research</h1>

<%= render 'form' %>

<%= link_to 'Back', publications_and_researches_path %>

app/views/publications_and_researches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Faculty:</strong>
  <%= @publications_and_research.faculty %>
</p>

<p>
  <strong>Organ name:</strong>
  <%= @publications_and_research.organ_name %>
</p>

<p>
  <strong>Material type:</strong>
  <%= @publications_and_research.material_type %>
</p>

<p>
  <strong>Publication date:</strong>
  <%= @publications_and_research.publication_date %>
</p>

<p>
  <strong>Authorship type:</strong>
  <%= @publications_and_research.authorship_type %>
</p>

<p>
  <strong>Co author:</strong>
  <%= @publications_and_research.co_author %>
</p>

<%= link_to 'Edit', edit_publications_and_research_path(@publications_and_research) %> |
<%= link_to 'Back', publications_and_researches_path %>