config/routes.rb
Fis::Application.routes.draw do
  resources :absences

  resources :char_refs

  resources :load_assign_in_others

  resources :publications_and_researches

  resources :professional_memberships

  resources :non_teaching_experiences

  resources :teaching_experiences

  resources :civil_service_and_govt_exams

  resources :educational_attainments

  resources :children

  resources :faculties

  resources :versions

  get "website/index"

  controller :website do
    get 'howto' => :howto
  end
  

  root :to => 'website#index', :as => 'website'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/absence.rb
class Absence < ActiveRecord::Base
  belongs_to :faculty
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/char_ref.rb
class CharRef < ActiveRecord::Base
  belongs_to :faculty
end

app/models/child.rb
class Child < ActiveRecord::Base
  belongs_to :faculty
end

app/models/educational_attainment.rb
class EducationalAttainment < ActiveRecord::Base
  belongs_to :faculty



end

app/models/faculty.rb
class Faculty < ActiveRecord::Base
	has_paper_trail :only => [:academic_rank,  :faculty_status, :faculty_status2, :pagibig, :tbi, :department]

	has_many :children, :dependent => :destroy

	validates :last_name, :first_name, :presence => true

	accepts_nested_attributes_for :children, :reject_if => :all_blank, :allow_destroy => true

	def fullname
		"#{self.last_name}, #{self.first_name}"
	end
end

app/models/load_assign_in_other.rb
class LoadAssignInOther < ActiveRecord::Base
  belongs_to :faculty
end

app/models/non_teaching_experience.rb
class NonTeachingExperience < ActiveRecord::Base
  belongs_to :faculty
end

app/models/professional_membership.rb
class ProfessionalMembership < ActiveRecord::Base
  belongs_to :faculty
end

app/models/publications_and_research.rb
class PublicationsAndResearch < ActiveRecord::Base
  belongs_to :faculty




end

app/models/teaching_experience.rb
class TeachingExperience < ActiveRecord::Base
  belongs_to :faculty
end

app/controllers/absences_controller.rb
class AbsencesController < InheritedResources::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/char_refs_controller.rb
class CharRefsController < InheritedResources::Base
end

app/controllers/children_controller.rb
class ChildrenController < InheritedResources::Base
end

app/controllers/faculties_controller.rb
class FacultiesController < InheritedResources::Base

	
end

app/controllers/versions_controller.rb
class VersionsController < InheritedResources::Base
end

app/controllers/website_controller.rb
class WebsiteController < ApplicationController
  def index
    @faculties = Faculty.take(15)
    @versions = PaperTrail::Version.all
  end

  def howto
  end
  
end

app/helpers/absences_helper.rb
module AbsencesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper


	
end

app/helpers/char_refs_helper.rb
module CharRefsHelper
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/views/absences/_form.html.erb
<%= form_for(@absence) do |f| %>
  <% if @absence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@absence.errors.count, "error") %> prohibited this absence from being saved:</h2>

      <ul>
      <% @absence.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :faculty_id %><br>
    <%= f.text_field :faculty_id %>
  </div>
  <div class="field">
    <%= f.label :date_of_absence %><br>
    <%= f.datetime_select :date_of_absence %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/absences/edit.html.erb
<h1>Editing absence</h1>

<%= render 'form' %>

<%= link_to 'Show', @absence %> |
<%= link_to 'Back', absences_path %>

app/views/absences/index.html.erb
<h1>Listing absences</h1>

<table>
  <thead>
    <tr>
      <th>Faculty</th>
      <th>Date of absence</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @absences.each do |absence| %>
      <tr>
        <td><%= absence.faculty %></td>
        <td><%= absence.date_of_absence %></td>
        <td><%= link_to 'Show', absence %></td>
        <td><%= link_to 'Edit', edit_absence_path(absence) %></td>
        <td><%= link_to 'Destroy', absence, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Absence', new_absence_path %>

app/views/absences/new.html.erb
<h1>New absence</h1>

<%= render 'form' %>

<%= link_to 'Back', absences_path %>

app/views/absences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Faculty:</strong>
  <%= @absence.faculty %>
</p>

<p>
  <strong>Date of absence:</strong>
  <%= @absence.date_of_absence %>
</p>

<%= link_to 'Edit', edit_absence_path(@absence) %> |
<%= link_to 'Back', absences_path %>

app/views/char_refs/_form.html.erb
<%= form_for(@char_ref) do |f| %>
  <% if @char_ref.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@char_ref.errors.count, "error") %> prohibited this char_ref from being saved:</h2>

      <ul>
      <% @char_ref.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :faculty_id %><br>
    <%= f.text_field :faculty_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :designation %><br>
    <%= f.text_field :designation %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :tel %><br>
    <%= f.text_field :tel %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/char_refs/edit.html.erb
<h1>Editing char_ref</h1>

<%= render 'form' %>

<%= link_to 'Show', @char_ref %> |
<%= link_to 'Back', char_refs_path %>

app/views/char_refs/index.html.erb
<h1>Listing char_refs</h1>

<table>
  <thead>
    <tr>
      <th>Faculty</th>
      <th>Name</th>
      <th>Designation</th>
      <th>Address</th>
      <th>Tel</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @char_refs.each do |char_ref| %>
      <tr>
        <td><%= char_ref.faculty %></td>
        <td><%= char_ref.name %></td>
        <td><%= char_ref.designation %></td>
        <td><%= char_ref.address %></td>
        <td><%= char_ref.tel %></td>
        <td><%= link_to 'Show', char_ref %></td>
        <td><%= link_to 'Edit', edit_char_ref_path(char_ref) %></td>
        <td><%= link_to 'Destroy', char_ref, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Char ref', new_char_ref_path %>

app/views/char_refs/new.html.erb
<h1>New char_ref</h1>

<%= render 'form' %>

<%= link_to 'Back', char_refs_path %>

app/views/char_refs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Faculty:</strong>
  <%= @char_ref.faculty %>
</p>

<p>
  <strong>Name:</strong>
  <%= @char_ref.name %>
</p>

<p>
  <strong>Designation:</strong>
  <%= @char_ref.designation %>
</p>

<p>
  <strong>Address:</strong>
  <%= @char_ref.address %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @char_ref.tel %>
</p>

<%= link_to 'Edit', edit_char_ref_path(@char_ref) %> |
<%= link_to 'Back', char_refs_path %>

app/views/faculties/_form.html.erb
<%= form_for(@faculty) do |f| %>
  <% if @faculty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@faculty.errors.count, "error") %> prohibited this faculty from being saved:</h2>

      <ul>
      <% @faculty.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :middle_name %><br>
    <%= f.text_field :middle_name %>
  </div>
  <div class="field">
    <%= f.label :present_address %><br>
    <%= f.text_field :present_address %>
  </div>
  <div class="field">
    <%= f.label :present_address_tel %><br>
    <%= f.text_field :present_address_tel %>
  </div>
  <div class="field">
    <%= f.label :perma_address %><br>
    <%= f.text_field :perma_address %>
  </div>
  <div class="field">
    <%= f.label :perma_address_tel %><br>
    <%= f.text_field :perma_address_tel %>
  </div>
  <div class="field">
    <%= f.label :nationality %><br>
    <%= f.text_field :nationality %>
  </div>
  <div class="field">
    <%= f.label :citizen %><br>
    <%= f.text_field :citizen %>
  </div>
  <div class="field">
    <%= f.label :birth_place %><br>
    <%= f.text_field :birth_place %>
  </div>
  <div class="field">
    <%= f.label :birth_date %><br>
    <%= f.datetime_select :birth_date %>
  </div>
  <div class="field">
    <%= f.label :civil_status %><br>
    <%= f.text_field :civil_status %>
  </div>
  <div class="field">
    <%= f.label :sex %><br>
    <%= f.text_field :sex %>
  </div>
  <div class="field">
    <%= f.label :spouse %><br>
    <%= f.text_field :spouse %>
  </div>
  <div class="field">
    <%= f.label :marriage_date %><br>
    <%= f.datetime_select :marriage_date %>
  </div>
  <div class="field">
    <%= f.label :occupation %><br>
    <%= f.text_field :occupation %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :employer %><br>
    <%= f.text_field :employer %>
  </div>
  <div class="field">
    <%= f.label :employer_tel %><br>
    <%= f.text_field :employer_tel %>
  </div>
  <div class="field">
    <%= f.label :no_of_child %><br>
    <%= f.number_field :no_of_child %>
  </div>
  <div class="field">
    <%= f.label :no_of_child_studying %><br>
    <%= f.number_field :no_of_child_studying %>
  </div>
  <div class="field">
    <%= f.label :no_of_child_working %><br>
    <%= f.number_field :no_of_child_working %>
  </div>
  <div class="field">
    <%= f.label :father_name %><br>
    <%= f.text_field :father_name %>
  </div>
  <div class="field">
    <%= f.label :father_age %><br>
    <%= f.number_field :father_age %>
  </div>
  <div class="field">
    <%= f.label :mother_name %><br>
    <%= f.text_field :mother_name %>
  </div>
  <div class="field">
    <%= f.label :mother_age %><br>
    <%= f.number_field :mother_age %>
  </div>
  <div class="field">
    <%= f.label :tin %><br>
    <%= f.text_field :tin %>
  </div>
  <div class="field">
    <%= f.label :sss %><br>
    <%= f.text_field :sss %>
  </div>
  <div class="field">
    <%= f.label :gsis %><br>
    <%= f.text_field :gsis %>
  </div>
  <div class="field">
    <%= f.label :philhealth %><br>
    <%= f.text_field :philhealth %>
  </div>
  <div class="field">
    <%= f.label :pro_license %><br>
    <%= f.text_field :pro_license %>
  </div>
  <div class="field">
    <%= f.label :resid_cert %><br>
    <%= f.text_field :resid_cert %>
  </div>
  <div class="field">
    <%= f.label :issued_at %><br>
    <%= f.text_field :issued_at %>
  </div>
  <div class="field">
    <%= f.label :issued_on %><br>
    <%= f.datetime_select :issued_on %>
  </div>
  <div class="field">
    <%= f.label :pro_license_expire %><br>
    <%= f.datetime_select :pro_license_expire %>
  </div>
  <div class="field">
    <%= f.label :academic_rank %><br>
    <%= f.text_field :academic_rank %>
  </div>
  <div class="field">
    <%= f.label :faculty_status %><br>
    <%= f.text_field :faculty_status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/faculties/edit.html.erb
<h1>Editing faculty</h1>

<%= render 'form' %>

<%= link_to 'Show', @faculty %> |
<%= link_to 'Back', faculties_path %>

app/views/faculties/index.html.erb
<h1>Listing faculties</h1>

<table>
  <thead>
    <tr>
      <th>Last name</th>
      <th>First name</th>
      <th>Middle name</th>
      <th>Present address</th>
      <th>Present address tel</th>
      <th>Perma address</th>
      <th>Perma address tel</th>
      <th>Nationality</th>
      <th>Citizen</th>
      <th>Birth place</th>
      <th>Birth date</th>
      <th>Civil status</th>
      <th>Sex</th>
      <th>Spouse</th>
      <th>Marriage date</th>
      <th>Occupation</th>
      <th>Position</th>
      <th>Employer</th>
      <th>Employer tel</th>
      <th>No of child</th>
      <th>No of child studying</th>
      <th>No of child working</th>
      <th>Father name</th>
      <th>Father age</th>
      <th>Mother name</th>
      <th>Mother age</th>
      <th>Tin</th>
      <th>Sss</th>
      <th>Gsis</th>
      <th>Philhealth</th>
      <th>Pro license</th>
      <th>Resid cert</th>
      <th>Issued at</th>
      <th>Issued on</th>
      <th>Pro license expire</th>
      <th>Academic rank</th>
      <th>Faculty status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @faculties.each do |faculty| %>
      <tr>
        <td><%= faculty.last_name %></td>
        <td><%= faculty.first_name %></td>
        <td><%= faculty.middle_name %></td>
        <td><%= faculty.present_address %></td>
        <td><%= faculty.present_address_tel %></td>
        <td><%= faculty.perma_address %></td>
        <td><%= faculty.perma_address_tel %></td>
        <td><%= faculty.nationality %></td>
        <td><%= faculty.citizen %></td>
        <td><%= faculty.birth_place %></td>
        <td><%= faculty.birth_date %></td>
        <td><%= faculty.civil_status %></td>
        <td><%= faculty.sex %></td>
        <td><%= faculty.spouse %></td>
        <td><%= faculty.marriage_date %></td>
        <td><%= faculty.occupation %></td>
        <td><%= faculty.position %></td>
        <td><%= faculty.employer %></td>
        <td><%= faculty.employer_tel %></td>
        <td><%= faculty.no_of_child %></td>
        <td><%= faculty.no_of_child_studying %></td>
        <td><%= faculty.no_of_child_working %></td>
        <td><%= faculty.father_name %></td>
        <td><%= faculty.father_age %></td>
        <td><%= faculty.mother_name %></td>
        <td><%= faculty.mother_age %></td>
        <td><%= faculty.tin %></td>
        <td><%= faculty.sss %></td>
        <td><%= faculty.gsis %></td>
        <td><%= faculty.philhealth %></td>
        <td><%= faculty.pro_license %></td>
        <td><%= faculty.resid_cert %></td>
        <td><%= faculty.issued_at %></td>
        <td><%= faculty.issued_on %></td>
        <td><%= faculty.pro_license_expire %></td>
        <td><%= faculty.academic_rank %></td>
        <td><%= faculty.faculty_status %></td>
        <td><%= link_to 'Show', faculty %></td>
        <td><%= link_to 'Edit', edit_faculty_path(faculty) %></td>
        <td><%= link_to 'Destroy', faculty, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Faculty', new_faculty_path %>

app/views/faculties/new.html.erb
<h1>New faculty</h1>

<%= render 'form' %>

<%= link_to 'Back', faculties_path %>

app/views/faculties/show.html.erb
<p id="notice"><%= notice %></td>

<div style="float:left; margin:20px; border: solid">
  <table>
<tr>
  <td><strong>Last name:</strong>
  <%= @faculty.last_name %></td>



  <td><strong>First name:</strong>
  <%= @faculty.first_name %></td>



  <td><strong>Middle name:</strong>
  <%= @faculty.middle_name %></td>
</tr>

</table>
<table>


<tr>
  <td><strong>Present address:</strong>
  <%= @faculty.present_address %></td>

</tr>

<tr>

  <td><strong>Present address tel.:</strong>
  <%= @faculty.present_address_tel %></td>
</tr>

<tr>
  <td><strong>Permanent address:</strong>
  <%= @faculty.perma_address %></td>

</tr>

<tr>

  <td><strong>Permanent address tel.:</strong>
  <%= @faculty.perma_address_tel %>
</td>
</tr>

</table>
<table>

<tr>
<td>
  <strong>Nationality:</strong>
  <%= @faculty.nationality %>
</td>

<td>
  <strong>Citizenship:</strong>
  <%= @faculty.citizen %>
</td>


<td>
  <strong>Birth place:</strong>
  <%= @faculty.birth_place %>
</td>

<td>
  <strong>Birth date:</strong>
  <%= @faculty.birth_date %>
</td></tr>

<tr><td>
  <strong>Civil status:</strong>
  <%= @faculty.civil_status %>
</td>

<td>
  <strong>Sex:</strong>
  <%= @faculty.sex %>
</td><td>
  <strong>Spouse:</strong>
  <%= @faculty.spouse %>
</td>

<td>
  <strong>Marriage date:</strong>
  <%= @faculty.marriage_date %>
</td></tr>

<tr><td>
  <strong>Occupation:</strong>
  <%= @faculty.occupation %>
</td>

<td>
  <strong>Position:</strong>
  <%= @faculty.position %>
</td>

<td>
  <strong>Employer:</strong>
  <%= @faculty.employer %>
</td>

<td>
  <strong>Employer tel.:</strong>
  <%= @faculty.employer_tel %>
</td></tr>

<tr><td>
  <strong>No. of children:</strong>
  <%= @faculty.no_of_child %>
</td>

<td>
  <strong>No. of children studying:</strong>
  <%= @faculty.no_of_child_studying %>
</td>

<td>
  <strong>No. of children working:</strong>
  <%= @faculty.no_of_child_working %>
</td></tr>

<tr><td>
  <strong>Father's name:</strong>
  <%= @faculty.father_name %>
</td>

<td>
  <strong>Father's age:</strong>
  <%= @faculty.father_age %>
</td>

<td>
  <strong>Mother's name:</strong>
  <%= @faculty.mother_name %>
</td>

<td>
  <strong>Mother's age:</strong>
  <%= @faculty.mother_age %>
</td></tr>

<tr><td>
  <strong>TIN:</strong>
  <%= @faculty.tin %>
</td>

<td>
  <strong>SSS:</strong>
  <%= @faculty.sss %>
</td>

<td>
  <strong>GSIS:</strong>
  <%= @faculty.gsis %>
</td></tr>

<tr><td>
  <strong>Philhealth:</strong>
  <%= @faculty.philhealth %>
</td>

<td>
  <strong>Residence certificate:</strong>
  <%= @faculty.resid_cert %>
</td>

</tr>

<tr><td>
  <strong>Professional license:</strong>
  <%= @faculty.pro_license %>
</td>

<td>
  <strong>Professional license expire:</strong>
  <%= @faculty.pro_license_expire %>
</td>




<td>
  <strong>Issued at:</strong>
  <%= @faculty.issued_at %>
</td>

<td>
  <strong>Issued on:</strong>
  <%= @faculty.issued_on %>
</td>


</tr>

<tr><td>
  <strong>Academic rank:</strong>
  <%= @faculty.academic_rank %>
</td>

<td>
  <strong>Faculty status:</strong>
  <%= @faculty.faculty_status %>
</td></tr>



</table>
</div>